# Generated by Django 5.0.6 on 2024-10-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('dob', models.DateField(max_length=250)),
                ('phone', models.IntegerField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
